# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_remove_company_place'),
        ('user', '0005_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profil',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
