# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_profil_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profil',
            new_name='UserProfile',
        ),
    ]
