# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_userprofile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='place',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
