# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 08:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
