# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_company_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='place',
        ),
    ]
